const pensum = [
    // ===== NIVEL 1 =====
    {
        id: "25941",
        nombre: "Cálculo Diferencial",
        creditos: 3,
        nivel: 1,
        estado: "no_cursada",
        syllabus: "syllabus/N1/CalculoDiferencial.pdf",
    },
    {
        id: "26130",
        nombre: "Matemáticas Discretas",
        creditos: 2,
        nivel: 1,
        estado: "no_cursada",
        syllabus: "syllabus/N1/MatematicasDiscretas.pdf",
    },
    {
        id: "25942",
        nombre: "Física Newtoniana",
        creditos: 3,
        nivel: 1,
        estado: "no_cursada",
        syllabus: "syllabus/N1/FisicaNewtoniana.pdf",
    },
    {
        id: "2",
        nombre: "Programación Básica",
        creditos: 3,
        nivel: 1,
        estado: "no_cursada",
        syllabus: "syllabus/N1/ProgramacionBasica.pdf",
    },
    {
        id: "26131",
        nombre: "Arquitectura de Computadores",
        creditos: 3,
        nivel: 1,
        estado: "no_cursada",
        syllabus: "syllabus/N1/ArquitecturaDeComputadores.pdf",
    },
    {
        id: "25943",
        nombre: "Seminario de Introducción a la Ingeniería",
        creditos: 1,
        nivel: 1,
        estado: "no_cursada",
        syllabus: "syllabus/N1/SeminarioDeIntroduccionAIngenieria.pdf",
    },
    {
        id: "4",
        nombre: "Cátedra Francisco José de Caldas",
        creditos: 1,
        nivel: 1,
        estado: "no_cursada",
        syllabus: "syllabus/N1/CatedraFranciscoJoseDeCaldas.pdf",
    },

    // ===== NIVEL 2 =====
    {
        id: "7",
        nombre: "Cálculo Integral",
        creditos: 3,
        nivel: 2,
        estado: "no_cursada",
        syllabus: "syllabus/N2/CalculoIntegral.pdf",
    },
    {
        id: "9",
        nombre: "Álgebra Lineal",
        creditos: 3,
        nivel: 2,
        estado: "no_cursada",
        syllabus: "syllabus/N2/AlgebraLineal.pdf",
    },
    {
        id: "25944",
        nombre: "Electromagnetismo",
        creditos: 3,
        nivel: 2,
        estado: "no_cursada",
        syllabus: "syllabus/N2/Electromagnetismo.pdf",
    },
    {
        id: "10",
        nombre: "Programación Orientada a Objetos",
        creditos: 3,
        nivel: 2,
        estado: "no_cursada",
        syllabus: "syllabus/N2/ProgramacionOrientadaAObjetos.pdf",
    },
    {
        id: "409",
        nombre: "Teoría de Sistemas",
        creditos: 2,
        nivel: 2,
        estado: "no_cursada",
        syllabus: "syllabus/N2/TeoriaDeSistemas.pdf",
    },
    {
        id: "8",
        nombre: "Historia y Cultura Colombiana",
        creditos: 2,
        nivel: 2,
        estado: "no_cursada",
        syllabus: "syllabus/N2/HistoriaYCulturaColombiana.pdf",
    },
    {
        id: "12",
        nombre: "Cátedra Democracia y Ciudadanía",
        creditos: 1,
        nivel: 2,
        estado: "no_cursada",
        syllabus: "syllabus/N2/CatedraDemocraciaYCiudadania.pdf",
    },

    // ===== NIVEL 3 =====
    {
        id: "16",
        nombre: "Cálculo Multivariado",
        creditos: 3,
        nivel: 3,
        estado: "no_cursada",
        syllabus: "syllabus/N3/CalculoMultivariado.pdf",
    },
    {
        id: "26132",
        nombre: "Probabilidad y Estadística",
        creditos: 3,
        nivel: 3,
        estado: "no_cursada",
        syllabus: "syllabus/N3/ProbabilidadYEstadistica.pdf",
    },
    {
        id: "423",
        nombre: "Ciencias de la Computación I",
        creditos: 3,
        nivel: 3,
        estado: "no_cursada",
        syllabus: "syllabus/N3/CienciasDeLaComputacionI.pdf",
    },
    {
        id: "410",
        nombre: "Programación Avanzada",
        creditos: 3,
        nivel: 3,
        estado: "no_cursada",
        syllabus: "syllabus/N3/ProgramacionAvanzada.pdf",
    },
    {
        id: "26133",
        nombre: "Análisis y Diseño de Sistemas",
        creditos: 2,
        nivel: 3,
        estado: "no_cursada",
        syllabus: "syllabus/N3/AnalisisYDisenoDeSistemas.pdf",
    },
    {
        id: "EXT-1",
        nombre: "Extrínseca I",
        creditos: 1,
        nivel: 3,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "26134",
        nombre: "Grupo de Trabajo",
        creditos: 1,
        nivel: 3,
        estado: "no_cursada",
        syllabus: "",
    },

    // ===== NIVEL 4 =====
    {
        id: "88",
        nombre: "Ecuaciones Diferenciales",
        creditos: 3,
        nivel: 4,
        estado: "no_cursada",
        syllabus: "syllabus/N4/EcuacionesDiferenciales.pdf",
    },
    {
        id: "26135",
        nombre: "Métodos Numéricos",
        creditos: 2,
        nivel: 4,
        estado: "no_cursada",
        syllabus: "syllabus/N4/MetodosNumericos.pdf",
    },
    {
        id: "26136",
        nombre: "Ciencias de la Computación II",
        creditos: 3,
        nivel: 4,
        estado: "no_cursada",
        syllabus: "syllabus/N4/CienciasDeLaComputacionII.pdf",
    },
    {
        id: "26137",
        nombre: "Modelos de Programación",
        creditos: 3,
        nivel: 4,
        estado: "no_cursada",
        syllabus: "syllabus/N4/ModelosDeProgramacion.pdf",
    },
    {
        id: "26138",
        nombre: "Investigación de Operaciones I",
        creditos: 2,
        nivel: 4,
        estado: "no_cursada",
        syllabus: "syllabus/N4/InvestigacionDeOperacionesI.pdf",
    },
    {
        id: "EXT-2",
        nombre: "Extrínseca II",
        creditos: 2,
        nivel: 4,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "47",
        nombre: "Economía",
        creditos: 2,
        nivel: 4,
        estado: "no_cursada",
        syllabus: "syllabus/N4/Economia.pdf",
    },

    // ===== NIVEL 5 =====
    {
        id: "415",
        nombre: "Matemáticas Especiales",
        creditos: 3,
        nivel: 5,
        estado: "no_cursada",
        syllabus: "syllabus/N5/MatematicasEspeciales.pdf",
    },
    {
        id: "437",
        nombre: "Fundamentos de Ingeniería de Software",
        creditos: 3,
        nivel: 5,
        estado: "no_cursada",
        syllabus: "syllabus/N5/FundamentosDeIngenieriaDeSoftware.pdf",
    },
    {
        id: "26139",
        nombre: "Fundamentos de Redes de Comunicaciones",
        creditos: 3,
        nivel: 5,
        estado: "no_cursada",
        syllabus: "syllabus/N5/FundamentosDeRedesDeComunicaciones.pdf",
    },
    {
        id: "26140",
        nombre: "Bases de Datos",
        creditos: 3,
        nivel: 5,
        estado: "no_cursada",
        syllabus: "syllabus/N5/BasesDeDatos.pdf",
    },
    {
        id: "26141",
        nombre: "Fundamentos de Ciencia de Sistemas",
        creditos: 3,
        nivel: 5,
        estado: "no_cursada",
        syllabus: "syllabus/N5/FundamentosDeCienciaDeSistemas.pdf",
    },
    {
        id: "26142",
        nombre: "Investigación de Operaciones II",
        creditos: 3,
        nivel: 5,
        estado: "no_cursada",
        syllabus: "syllabus/N5/InvestigacionDeOperacionesII.pdf",
    },

    // ===== NIVEL 6 =====
    {
        id: "26143",
        nombre: "Procesos Estocásticos",
        creditos: 3,
        nivel: 6,
        estado: "no_cursada",
        syllabus: "syllabus/N6/ProcesosEstocasticos.pdf",
    },
    {
        id: "RF-OBL-1",
        nombre: "Curso Obligatorio I RF",
        creditos: 3,
        nivel: 6,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "RF-OBL-2",
        nombre: "Curso Obligatorio II RF",
        creditos: 3,
        nivel: 6,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "RF-FLEX-1",
        nombre: "Curso Electivo Flexible I RF",
        creditos: 4,
        nivel: 6,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "EXT-3",
        nombre: "Extrínseca III",
        creditos: 2,
        nivel: 6,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "53",
        nombre: "Ingeniería Económica",
        creditos: 2,
        nivel: 6,
        estado: "no_cursada",
        syllabus: "syllabus/N6/IngenieriaEconomica.pdf",
    },

    // ===== NIVEL 7 =====
    {
        id: "RF-OBL-3",
        nombre: "Curso Obligatorio III RF",
        creditos: 3,
        nivel: 7,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "RF-OBL-4",
        nombre: "Curso Obligatorio IV RF",
        creditos: 3,
        nivel: 7,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "RF-FLEX-2",
        nombre: "Curso Electivo Flexible II RF",
        creditos: 4,
        nivel: 7,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "26148",
        nombre: "Sistemas Operativos",
        creditos: 3,
        nivel: 7,
        estado: "no_cursada",
        syllabus: "syllabus/N7/SistemasOperativos.pdf",
    },
    {
        id: "26149",
        nombre: "Teoría de la Información",
        creditos: 2,
        nivel: 7,
        estado: "no_cursada",
        syllabus: "syllabus/N7/TeoriaDeLaInformacion.pdf",
    },
    {
        id: "26150",
        nombre: "Metodología de la Investigación",
        creditos: 2,
        nivel: 7,
        estado: "no_cursada",
        syllabus: "syllabus/N7/MetodologiaDeLaInvestigacion.pdf",
    },

    // ===== NIVEL 8 =====
    {
        id: "RF-ELEC-1",
        nombre: "Curso Electivo I RF",
        creditos: 4,
        nivel: 8,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "RF-ELEC-2",
        nombre: "Curso Electivo II RF",
        creditos: 4,
        nivel: 8,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "RF-FLEX-3",
        nombre: "Curso Electivo Flexible III RF",
        creditos: 4,
        nivel: 8,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "25956",
        nombre: "Formulación y Evaluación de Proyectos",
        creditos: 2,
        nivel: 8,
        estado: "no_cursada",
        syllabus: "syllabus/N8/FormulacionYEvaluacionDeProyectos.pdf",
    },
    {
        id: "26151",
        nombre: "Grupo de Investigación",
        creditos: 1,
        nivel: 8,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "26152",
        nombre: "Trabajo de Grado I",
        creditos: 1,
        nivel: 8,
        estado: "no_cursada",
        syllabus: "syllabus/N8/TrabajoDeGradoI.pdf",
    },

    // ===== NIVEL 9 =====
    {
        id: "RF-ELEC-3",
        nombre: "Curso Electivo III RF",
        creditos: 4,
        nivel: 9,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "RF-ELEC-4",
        nombre: "Curso Electivo IV RF",
        creditos: 4,
        nivel: 9,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "RF-FLEX-4",
        nombre: "Curso Electivo Flexible IV RF",
        creditos: 4,
        nivel: 9,
        estado: "no_cursada",
        syllabus: "",
    },
    {
        id: "18",
        nombre: "Ética y Bioética",
        creditos: 2,
        nivel: 9,
        estado: "no_cursada",
        syllabus: "syllabus/N9/EticaYBioetica.pdf",
    },
    {
        id: "26153",
        nombre: "Trabajo de Grado II",
        creditos: 3,
        nivel: 9,
        estado: "no_cursada",
        syllabus: "syllabus/N9/TrabajoDeGradoII.pdf",
    },
];